---
title: "Challenge"
author: "Brandon Zimlich-Vining"
date: "9/14/2019"
output:
  pdf_document: default
  word_document: default
  html_document: default
---

- List
- list
- list

1. _list_
1. _list_
1. _list_

* bullet
* bullet
* bullet

# ggplot
ggplot is soooo radical dude.....lol  

back ticks then in brackets, the language and then name for chunk

```{r first_chunk}
gapminder <- read.table("gapminder.txt", header =TRUE)
head(gapminder)
```

```{r second_chunk, echo=FALSE}
library(ggplot2)
e_rows=startsWith(as.vector(gapminder$country), c('E') )
e_countries <- gapminder[e_rows, ]
ggplot(data = e_countries, aes(x = year, y = pop/1000000, fill=continent)) +
  geom_bar(stat="identity") + facet_wrap( ~ country) +
  labs(
    x = "Year",                     # x axis title
    y = "Population (Million)",     # y axis title
    title = "Figure 1",             # main title of figure
    fill = "Continent"              # title of legend
  ) +
  theme(axis.text.x=element_text(angle=45), axis.ticks.x=element_blank()) +
  theme_bw()
```

The mean life expectancy of Sweden is `r mean(gapminder[gapminder$country == "Sweden","lifeExp"])`